// ==========================================
// WorkFlow Pro — Mock / Seed Data
// ==========================================

import type {
  User, Branch, AttendanceRecord, TaskTemplate,
  Task, TaskSubmission, SubmissionFile, Notification,
} from './types';

// ---- Branches ----

export const mockBranches: Branch[] = [
  {
    id: 'branch-001',
    name: 'สำนักงานใหญ่ กรุงเทพฯ',
    address: '123 ถนนสุขุมวิท แขวงคลองตัน เขตคลองเตย กรุงเทพมหานคร 10110',
    latitude: 13.7234,
    longitude: 100.5678,
    geofence_radius_meters: 100,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'branch-002',
    name: 'สาขาเชียงใหม่',
    address: '456 ถนนนิมมานเหมินท์ ตำบลสุเทพ อำเภอเมืองเชียงใหม่ 50200',
    latitude: 18.7953,
    longitude: 98.9683,
    geofence_radius_meters: 150,
    created_at: '2025-02-01T00:00:00Z',
  },
  {
    id: 'branch-003',
    name: 'สาขาภูเก็ต',
    address: '789 ถนนทวีวงศ์ ตำบลป่าตอง อำเภอกะทู้ ภูเก็ต 83150',
    latitude: 7.8804,
    longitude: 98.3923,
    geofence_radius_meters: 200,
    created_at: '2025-03-01T00:00:00Z',
  },
];

// ---- Users ----

export const mockUsers: User[] = [
  {
    id: 'user-001',
    full_name: 'วิชัย สมบูรณ์ศิริ',
    email: 'wichai@workflow.co',
    phone: '081-234-5678',
    role: 'admin',
    branch_id: 'branch-001',
    team_id: 'team-mgmt',
    status: 'active',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-002',
    full_name: 'สุชาติ พงศ์ประดิษฐ์',
    email: 'suchat@workflow.co',
    phone: '082-345-6789',
    role: 'manager',
    branch_id: 'branch-001',
    team_id: 'team-mgmt',
    status: 'active',
    created_at: '2025-01-15T00:00:00Z',
  },
  {
    id: 'user-003',
    full_name: 'ณัฐวดี จันทร์เพ็ญ',
    email: 'nattawadee@workflow.co',
    phone: '083-456-7890',
    role: 'manager',
    branch_id: 'branch-002',
    team_id: 'team-mgmt',
    status: 'active',
    created_at: '2025-02-01T00:00:00Z',
  },
  {
    id: 'user-004',
    full_name: 'ปิยะ ธนวัฒน์',
    email: 'piya@workflow.co',
    phone: '084-567-8901',
    role: 'employee',
    branch_id: 'branch-001',
    team_id: 'team-ops',
    status: 'active',
    created_at: '2025-01-20T00:00:00Z',
  },
  {
    id: 'user-005',
    full_name: 'กมลชนก ศรีวิไล',
    email: 'kamonchanok@workflow.co',
    phone: '085-678-9012',
    role: 'employee',
    branch_id: 'branch-001',
    team_id: 'team-ops',
    status: 'active',
    created_at: '2025-01-25T00:00:00Z',
  },
  {
    id: 'user-006',
    full_name: 'ธนพล เจริญกิจ',
    email: 'thanapol@workflow.co',
    phone: '086-789-0123',
    role: 'employee',
    branch_id: 'branch-002',
    team_id: 'team-sales',
    status: 'active',
    created_at: '2025-02-10T00:00:00Z',
  },
  {
    id: 'user-007',
    full_name: 'อรุณี มาลัยทอง',
    email: 'arunee@workflow.co',
    phone: '087-890-1234',
    role: 'employee',
    branch_id: 'branch-002',
    team_id: 'team-sales',
    status: 'active',
    created_at: '2025-02-15T00:00:00Z',
  },
  {
    id: 'user-008',
    full_name: 'ชัยวัฒน์ สุขสวัสดิ์',
    email: 'chaiwat@workflow.co',
    phone: '088-901-2345',
    role: 'employee',
    branch_id: 'branch-003',
    team_id: 'team-ops',
    status: 'active',
    created_at: '2025-03-05T00:00:00Z',
  },
];

// ---- Task Templates ----

export const mockTaskTemplates: TaskTemplate[] = [
  {
    id: 'tmpl-001',
    title: 'ทำความสะอาดพื้นที่ส่วนกลาง',
    description: 'ทำความสะอาดพื้นที่ส่วนกลางของสำนักงาน รวมถึงห้องประชุม ห้องครัว และห้องน้ำ ให้เรียบร้อยตามมาตรฐาน',
    priority: 'medium',
    proof_type_required: 'photo',
    requires_approval: true,
    recurrence_rule: 'daily',
    checklist_json: [
      { id: 'cl-001', label: 'กวาดและถูพื้น', completed: false },
      { id: 'cl-002', label: 'เช็ดโต๊ะและเก้าอี้', completed: false },
      { id: 'cl-003', label: 'ทำความสะอาดห้องน้ำ', completed: false },
      { id: 'cl-004', label: 'เปลี่ยนถุงขยะ', completed: false },
    ],
    branch_id: 'branch-001',
    created_at: '2025-03-01T00:00:00Z',
  },
  {
    id: 'tmpl-002',
    title: 'ตรวจสต็อกสินค้า',
    description: 'ตรวจนับจำนวนสินค้าคงเหลือในคลัง เปรียบเทียบกับระบบ และรายงานความแตกต่าง',
    priority: 'high',
    proof_type_required: 'photo',
    requires_approval: true,
    recurrence_rule: 'weekly',
    checklist_json: [
      { id: 'cl-005', label: 'นับสินค้าหมวด A', completed: false },
      { id: 'cl-006', label: 'นับสินค้าหมวด B', completed: false },
      { id: 'cl-007', label: 'บันทึกผลในแบบฟอร์ม', completed: false },
      { id: 'cl-008', label: 'ถ่ายรูปชั้นสินค้า', completed: false },
    ],
    branch_id: 'branch-001',
    created_at: '2025-03-01T00:00:00Z',
  },
  {
    id: 'tmpl-003',
    title: 'ส่งรายงานยอดขายประจำวัน',
    description: 'รวบรวมยอดขายประจำวัน จัดทำรายงานสรุป และส่งให้ผู้จัดการสาขา',
    priority: 'high',
    proof_type_required: 'text',
    requires_approval: true,
    recurrence_rule: 'daily',
    checklist_json: [],
    branch_id: 'branch-002',
    created_at: '2025-03-15T00:00:00Z',
  },
  {
    id: 'tmpl-004',
    title: 'ตรวจเช็คอุปกรณ์สำนักงาน',
    description: 'ตรวจสอบสภาพอุปกรณ์สำนักงาน เช่น เครื่องพิมพ์ เครื่องถ่ายเอกสาร แอร์ และรายงานเมื่อพบปัญหา',
    priority: 'low',
    proof_type_required: 'checklist',
    requires_approval: false,
    recurrence_rule: 'weekly',
    checklist_json: [
      { id: 'cl-009', label: 'ตรวจเครื่องพิมพ์', completed: false },
      { id: 'cl-010', label: 'ตรวจเครื่องถ่ายเอกสาร', completed: false },
      { id: 'cl-011', label: 'ตรวจระบบแอร์', completed: false },
      { id: 'cl-012', label: 'ตรวจระบบไฟฟ้า', completed: false },
      { id: 'cl-013', label: 'ตรวจระบบน้ำ', completed: false },
    ],
    branch_id: 'branch-001',
    created_at: '2025-03-10T00:00:00Z',
  },
  {
    id: 'tmpl-005',
    title: 'ถ่ายภาพหน้าร้านประจำวัน',
    description: 'ถ่ายภาพหน้าร้านและบริเวณรอบนอกเพื่อยืนยันความเรียบร้อยของหน้าร้าน',
    priority: 'medium',
    proof_type_required: 'photo',
    requires_approval: false,
    recurrence_rule: 'daily',
    checklist_json: [],
    branch_id: 'branch-003',
    created_at: '2025-03-20T00:00:00Z',
  },
];

// ---- Helper: get today's date string ----
function getToday(): string {
  return new Date().toISOString().split('T')[0];
}

function getDateOffset(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

// ---- Tasks ----

export const mockTasks: Task[] = [
  // Today's tasks for user-004 (ปิยะ)
  {
    id: 'task-001',
    template_id: 'tmpl-001',
    assigned_to: 'user-004',
    due_date: getToday(),
    status: 'pending',
    checklist_state: [
      { id: 'cl-001', label: 'กวาดและถูพื้น', completed: false },
      { id: 'cl-002', label: 'เช็ดโต๊ะและเก้าอี้', completed: false },
      { id: 'cl-003', label: 'ทำความสะอาดห้องน้ำ', completed: false },
      { id: 'cl-004', label: 'เปลี่ยนถุงขยะ', completed: false },
    ],
    created_at: getToday() + 'T00:00:00Z',
  },
  {
    id: 'task-002',
    template_id: 'tmpl-004',
    assigned_to: 'user-004',
    due_date: getToday(),
    status: 'in_progress',
    checklist_state: [
      { id: 'cl-009', label: 'ตรวจเครื่องพิมพ์', completed: true },
      { id: 'cl-010', label: 'ตรวจเครื่องถ่ายเอกสาร', completed: true },
      { id: 'cl-011', label: 'ตรวจระบบแอร์', completed: false },
      { id: 'cl-012', label: 'ตรวจระบบไฟฟ้า', completed: false },
      { id: 'cl-013', label: 'ตรวจระบบน้ำ', completed: false },
    ],
    created_at: getToday() + 'T00:00:00Z',
  },
  // Yesterday's completed task for user-004
  {
    id: 'task-003',
    template_id: 'tmpl-001',
    assigned_to: 'user-004',
    due_date: getDateOffset(-1),
    status: 'approved',
    checklist_state: [
      { id: 'cl-001', label: 'กวาดและถูพื้น', completed: true },
      { id: 'cl-002', label: 'เช็ดโต๊ะและเก้าอี้', completed: true },
      { id: 'cl-003', label: 'ทำความสะอาดห้องน้ำ', completed: true },
      { id: 'cl-004', label: 'เปลี่ยนถุงขยะ', completed: true },
    ],
    created_at: getDateOffset(-1) + 'T00:00:00Z',
  },
  // Tasks for user-005 (กมลชนก)
  {
    id: 'task-004',
    template_id: 'tmpl-002',
    assigned_to: 'user-005',
    due_date: getToday(),
    status: 'submitted',
    checklist_state: [
      { id: 'cl-005', label: 'นับสินค้าหมวด A', completed: true },
      { id: 'cl-006', label: 'นับสินค้าหมวด B', completed: true },
      { id: 'cl-007', label: 'บันทึกผลในแบบฟอร์ม', completed: true },
      { id: 'cl-008', label: 'ถ่ายรูปชั้นสินค้า', completed: true },
    ],
    created_at: getToday() + 'T00:00:00Z',
  },
  {
    id: 'task-005',
    template_id: 'tmpl-001',
    assigned_to: 'user-005',
    due_date: getToday(),
    status: 'pending',
    checklist_state: [
      { id: 'cl-001', label: 'กวาดและถูพื้น', completed: false },
      { id: 'cl-002', label: 'เช็ดโต๊ะและเก้าอี้', completed: false },
      { id: 'cl-003', label: 'ทำความสะอาดห้องน้ำ', completed: false },
      { id: 'cl-004', label: 'เปลี่ยนถุงขยะ', completed: false },
    ],
    created_at: getToday() + 'T00:00:00Z',
  },
  // Tasks for user-006 (ธนพล - เชียงใหม่)
  {
    id: 'task-006',
    template_id: 'tmpl-003',
    assigned_to: 'user-006',
    due_date: getToday(),
    status: 'pending',
    checklist_state: [],
    created_at: getToday() + 'T00:00:00Z',
  },
  {
    id: 'task-007',
    template_id: 'tmpl-003',
    assigned_to: 'user-006',
    due_date: getDateOffset(-1),
    status: 'overdue',
    checklist_state: [],
    created_at: getDateOffset(-1) + 'T00:00:00Z',
  },
  // Tasks for user-007 (อรุณี)
  {
    id: 'task-008',
    template_id: 'tmpl-003',
    assigned_to: 'user-007',
    due_date: getToday(),
    status: 'approved',
    checklist_state: [],
    created_at: getToday() + 'T00:00:00Z',
  },
  // Tasks for user-008 (ชัยวัฒน์ - ภูเก็ต)
  {
    id: 'task-009',
    template_id: 'tmpl-005',
    assigned_to: 'user-008',
    due_date: getToday(),
    status: 'pending',
    checklist_state: [],
    created_at: getToday() + 'T00:00:00Z',
  },
  // Overdue task for user-004
  {
    id: 'task-010',
    template_id: 'tmpl-002',
    assigned_to: 'user-004',
    due_date: getDateOffset(-2),
    status: 'overdue',
    checklist_state: [
      { id: 'cl-005', label: 'นับสินค้าหมวด A', completed: false },
      { id: 'cl-006', label: 'นับสินค้าหมวด B', completed: false },
      { id: 'cl-007', label: 'บันทึกผลในแบบฟอร์ม', completed: false },
      { id: 'cl-008', label: 'ถ่ายรูปชั้นสินค้า', completed: false },
    ],
    created_at: getDateOffset(-2) + 'T00:00:00Z',
  },
  // Rejected task for user-005
  {
    id: 'task-011',
    template_id: 'tmpl-001',
    assigned_to: 'user-005',
    due_date: getDateOffset(-1),
    status: 'rejected',
    checklist_state: [
      { id: 'cl-001', label: 'กวาดและถูพื้น', completed: true },
      { id: 'cl-002', label: 'เช็ดโต๊ะและเก้าอี้', completed: true },
      { id: 'cl-003', label: 'ทำความสะอาดห้องน้ำ', completed: false },
      { id: 'cl-004', label: 'เปลี่ยนถุงขยะ', completed: true },
    ],
    created_at: getDateOffset(-1) + 'T00:00:00Z',
  },
  // More tasks for various users (this week)
  {
    id: 'task-012',
    template_id: 'tmpl-001',
    assigned_to: 'user-006',
    due_date: getDateOffset(1),
    status: 'pending',
    checklist_state: [
      { id: 'cl-001', label: 'กวาดและถูพื้น', completed: false },
      { id: 'cl-002', label: 'เช็ดโต๊ะและเก้าอี้', completed: false },
      { id: 'cl-003', label: 'ทำความสะอาดห้องน้ำ', completed: false },
      { id: 'cl-004', label: 'เปลี่ยนถุงขยะ', completed: false },
    ],
    created_at: getToday() + 'T00:00:00Z',
  },
  {
    id: 'task-013',
    template_id: 'tmpl-005',
    assigned_to: 'user-008',
    due_date: getDateOffset(1),
    status: 'pending',
    checklist_state: [],
    created_at: getToday() + 'T00:00:00Z',
  },
  {
    id: 'task-014',
    template_id: 'tmpl-004',
    assigned_to: 'user-005',
    due_date: getDateOffset(2),
    status: 'pending',
    checklist_state: [
      { id: 'cl-009', label: 'ตรวจเครื่องพิมพ์', completed: false },
      { id: 'cl-010', label: 'ตรวจเครื่องถ่ายเอกสาร', completed: false },
      { id: 'cl-011', label: 'ตรวจระบบแอร์', completed: false },
      { id: 'cl-012', label: 'ตรวจระบบไฟฟ้า', completed: false },
      { id: 'cl-013', label: 'ตรวจระบบน้ำ', completed: false },
    ],
    created_at: getToday() + 'T00:00:00Z',
  },
  {
    id: 'task-015',
    template_id: 'tmpl-002',
    assigned_to: 'user-007',
    due_date: getDateOffset(3),
    status: 'pending',
    checklist_state: [
      { id: 'cl-005', label: 'นับสินค้าหมวด A', completed: false },
      { id: 'cl-006', label: 'นับสินค้าหมวด B', completed: false },
      { id: 'cl-007', label: 'บันทึกผลในแบบฟอร์ม', completed: false },
      { id: 'cl-008', label: 'ถ่ายรูปชั้นสินค้า', completed: false },
    ],
    created_at: getToday() + 'T00:00:00Z',
  },
];

// ---- Attendance Records ----

export const mockAttendanceRecords: AttendanceRecord[] = [
  // Today: user-004 checked in on time
  {
    id: 'att-001',
    user_id: 'user-004',
    branch_id: 'branch-001',
    type: 'check_in',
    photo_url: '/mock/check-in-1.jpg',
    latitude: 13.7235,
    longitude: 100.5679,
    gps_accuracy: 15,
    verified_in_geofence: true,
    device_info: { userAgent: 'Mozilla/5.0 Mobile', platform: 'Android', screenWidth: 393, screenHeight: 851 },
    created_at: getToday() + 'T08:25:00Z',
    server_timestamp: getToday() + 'T08:25:01Z',
    status: 'checked_in',
    notes: '',
  },
  // Today: user-005 checked in late
  {
    id: 'att-002',
    user_id: 'user-005',
    branch_id: 'branch-001',
    type: 'check_in',
    photo_url: '/mock/check-in-2.jpg',
    latitude: 13.7236,
    longitude: 100.5680,
    gps_accuracy: 20,
    verified_in_geofence: true,
    device_info: { userAgent: 'Mozilla/5.0 Mobile', platform: 'iOS', screenWidth: 390, screenHeight: 844 },
    created_at: getToday() + 'T09:05:00Z',
    server_timestamp: getToday() + 'T09:05:02Z',
    status: 'late',
    notes: 'เข้างานสาย 35 นาที',
  },
  // Today: user-006 checked in (Chiang Mai)
  {
    id: 'att-003',
    user_id: 'user-006',
    branch_id: 'branch-002',
    type: 'check_in',
    photo_url: '/mock/check-in-3.jpg',
    latitude: 18.7954,
    longitude: 98.9684,
    gps_accuracy: 10,
    verified_in_geofence: true,
    device_info: { userAgent: 'Mozilla/5.0 Mobile', platform: 'Android', screenWidth: 412, screenHeight: 915 },
    created_at: getToday() + 'T08:28:00Z',
    server_timestamp: getToday() + 'T08:28:01Z',
    status: 'checked_in',
    notes: '',
  },
  // Yesterday: user-004 full day
  {
    id: 'att-004',
    user_id: 'user-004',
    branch_id: 'branch-001',
    type: 'check_in',
    photo_url: '/mock/check-in-4.jpg',
    latitude: 13.7235,
    longitude: 100.5679,
    gps_accuracy: 12,
    verified_in_geofence: true,
    device_info: { userAgent: 'Mozilla/5.0 Mobile', platform: 'Android', screenWidth: 393, screenHeight: 851 },
    created_at: getDateOffset(-1) + 'T08:20:00Z',
    server_timestamp: getDateOffset(-1) + 'T08:20:01Z',
    status: 'checked_in',
    notes: '',
  },
  {
    id: 'att-005',
    user_id: 'user-004',
    branch_id: 'branch-001',
    type: 'check_out',
    photo_url: '/mock/check-out-1.jpg',
    latitude: 13.7235,
    longitude: 100.5679,
    gps_accuracy: 18,
    verified_in_geofence: true,
    device_info: { userAgent: 'Mozilla/5.0 Mobile', platform: 'Android', screenWidth: 393, screenHeight: 851 },
    created_at: getDateOffset(-1) + 'T17:35:00Z',
    server_timestamp: getDateOffset(-1) + 'T17:35:02Z',
    status: 'checked_out',
    notes: '',
  },
  // Yesterday: user-005 full day (late)
  {
    id: 'att-006',
    user_id: 'user-005',
    branch_id: 'branch-001',
    type: 'check_in',
    photo_url: '/mock/check-in-5.jpg',
    latitude: 13.7234,
    longitude: 100.5677,
    gps_accuracy: 25,
    verified_in_geofence: true,
    device_info: { userAgent: 'Mozilla/5.0 Mobile', platform: 'iOS', screenWidth: 390, screenHeight: 844 },
    created_at: getDateOffset(-1) + 'T08:55:00Z',
    server_timestamp: getDateOffset(-1) + 'T08:55:01Z',
    status: 'late',
    notes: 'เข้างานสาย 25 นาที',
  },
  {
    id: 'att-007',
    user_id: 'user-005',
    branch_id: 'branch-001',
    type: 'check_out',
    photo_url: '/mock/check-out-2.jpg',
    latitude: 13.7234,
    longitude: 100.5677,
    gps_accuracy: 22,
    verified_in_geofence: true,
    device_info: { userAgent: 'Mozilla/5.0 Mobile', platform: 'iOS', screenWidth: 390, screenHeight: 844 },
    created_at: getDateOffset(-1) + 'T17:30:00Z',
    server_timestamp: getDateOffset(-1) + 'T17:30:01Z',
    status: 'checked_out',
    notes: '',
  },
  // Failed attempt: user-008 out of area
  {
    id: 'att-008',
    user_id: 'user-008',
    branch_id: 'branch-003',
    type: 'check_in',
    photo_url: '/mock/check-in-6.jpg',
    latitude: 7.8900,
    longitude: 98.4000,
    gps_accuracy: 50,
    verified_in_geofence: false,
    device_info: { userAgent: 'Mozilla/5.0 Mobile', platform: 'Android', screenWidth: 360, screenHeight: 780 },
    created_at: getDateOffset(-1) + 'T08:30:00Z',
    server_timestamp: getDateOffset(-1) + 'T08:30:01Z',
    status: 'out_of_area',
    notes: 'อยู่ห่างจากสาขา 850 เมตร',
  },
  // 2 days ago records
  {
    id: 'att-009',
    user_id: 'user-004',
    branch_id: 'branch-001',
    type: 'check_in',
    photo_url: '/mock/check-in-7.jpg',
    latitude: 13.7235,
    longitude: 100.5679,
    gps_accuracy: 10,
    verified_in_geofence: true,
    device_info: { userAgent: 'Mozilla/5.0 Mobile', platform: 'Android', screenWidth: 393, screenHeight: 851 },
    created_at: getDateOffset(-2) + 'T08:15:00Z',
    server_timestamp: getDateOffset(-2) + 'T08:15:01Z',
    status: 'checked_in',
    notes: '',
  },
  {
    id: 'att-010',
    user_id: 'user-004',
    branch_id: 'branch-001',
    type: 'check_out',
    photo_url: '/mock/check-out-3.jpg',
    latitude: 13.7235,
    longitude: 100.5679,
    gps_accuracy: 14,
    verified_in_geofence: true,
    device_info: { userAgent: 'Mozilla/5.0 Mobile', platform: 'Android', screenWidth: 393, screenHeight: 851 },
    created_at: getDateOffset(-2) + 'T17:40:00Z',
    server_timestamp: getDateOffset(-2) + 'T17:40:01Z',
    status: 'checked_out',
    notes: '',
  },
];

// ---- Task Submissions ----

export const mockSubmissions: TaskSubmission[] = [
  {
    id: 'sub-001',
    task_id: 'task-003',
    submitted_by: 'user-004',
    note: 'ทำความสะอาดเรียบร้อยแล้วครับ',
    submitted_at: getDateOffset(-1) + 'T14:30:00Z',
    review_status: 'approved',
    review_comment: 'เรียบร้อยดี',
    reviewed_by: 'user-002',
    reviewed_at: getDateOffset(-1) + 'T15:00:00Z',
    created_at: getDateOffset(-1) + 'T14:30:00Z',
  },
  {
    id: 'sub-002',
    task_id: 'task-004',
    submitted_by: 'user-005',
    note: 'ตรวจนับสต็อกเรียบร้อย สินค้าหมวด A ตรงกับระบบ หมวด B ขาด 3 ชิ้น',
    submitted_at: getToday() + 'T11:00:00Z',
    review_status: 'pending',
    created_at: getToday() + 'T11:00:00Z',
  },
  {
    id: 'sub-003',
    task_id: 'task-011',
    submitted_by: 'user-005',
    note: 'ทำความสะอาดแล้ว',
    submitted_at: getDateOffset(-1) + 'T16:00:00Z',
    review_status: 'rejected',
    review_comment: 'ห้องน้ำยังไม่ได้ทำความสะอาด กรุณาทำให้ครบทุกรายการ',
    reviewed_by: 'user-002',
    reviewed_at: getDateOffset(-1) + 'T16:30:00Z',
    created_at: getDateOffset(-1) + 'T16:00:00Z',
  },
  {
    id: 'sub-004',
    task_id: 'task-008',
    submitted_by: 'user-007',
    note: 'รายงานยอดขายวันนี้: รวม 45,230 บาท, เป้า 50,000 บาท (90.46%)',
    submitted_at: getToday() + 'T16:00:00Z',
    review_status: 'approved',
    review_comment: 'ยอดใกล้เป้าดี',
    reviewed_by: 'user-003',
    reviewed_at: getToday() + 'T16:30:00Z',
    created_at: getToday() + 'T16:00:00Z',
  },
];

// ---- Submission Files ----

export const mockSubmissionFiles: SubmissionFile[] = [
  {
    id: 'file-001',
    submission_id: 'sub-001',
    file_url: '/mock/proof-clean-1.jpg',
    file_type: 'image',
    created_at: getDateOffset(-1) + 'T14:30:00Z',
  },
  {
    id: 'file-002',
    submission_id: 'sub-001',
    file_url: '/mock/proof-clean-2.jpg',
    file_type: 'image',
    created_at: getDateOffset(-1) + 'T14:30:00Z',
  },
  {
    id: 'file-003',
    submission_id: 'sub-002',
    file_url: '/mock/proof-stock-1.jpg',
    file_type: 'image',
    created_at: getToday() + 'T11:00:00Z',
  },
  {
    id: 'file-004',
    submission_id: 'sub-003',
    file_url: '/mock/proof-clean-3.jpg',
    file_type: 'image',
    created_at: getDateOffset(-1) + 'T16:00:00Z',
  },
];

// ---- Notifications ----

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    user_id: 'user-004',
    title: 'งานใหม่ได้รับมอบหมาย',
    message: 'คุณได้รับมอบหมายงาน "ทำความสะอาดพื้นที่ส่วนกลาง" สำหรับวันนี้',
    type: 'task',
    is_read: false,
    link: '/employee/tasks/task-001',
    created_at: getToday() + 'T07:00:00Z',
  },
  {
    id: 'notif-002',
    user_id: 'user-004',
    title: 'งานเลยกำหนดส่ง',
    message: 'งาน "ตรวจสต็อกสินค้า" เลยกำหนดส่งแล้ว กรุณาดำเนินการโดยเร็ว',
    type: 'task',
    is_read: false,
    link: '/employee/tasks/task-010',
    created_at: getToday() + 'T08:00:00Z',
  },
  {
    id: 'notif-003',
    user_id: 'user-005',
    title: 'งานไม่ผ่านการตรวจ',
    message: 'งาน "ทำความสะอาดพื้นที่ส่วนกลาง" ไม่ผ่านการตรวจ: ห้องน้ำยังไม่ได้ทำความสะอาด',
    type: 'review',
    is_read: true,
    link: '/employee/tasks/task-011',
    created_at: getDateOffset(-1) + 'T16:35:00Z',
  },
  {
    id: 'notif-004',
    user_id: 'user-002',
    title: 'งานรอตรวจสอบ',
    message: 'กมลชนก ศรีวิไล ส่งหลักฐานงาน "ตรวจสต็อกสินค้า" รอการตรวจสอบ',
    type: 'review',
    is_read: false,
    link: '/manager/review/sub-002',
    created_at: getToday() + 'T11:05:00Z',
  },
  {
    id: 'notif-005',
    user_id: 'user-002',
    title: 'พนักงานเข้างานสาย',
    message: 'กมลชนก ศรีวิไล เข้างานสาย 35 นาที',
    type: 'attendance',
    is_read: false,
    link: '/manager/attendance',
    created_at: getToday() + 'T09:06:00Z',
  },
  {
    id: 'notif-006',
    user_id: 'user-002',
    title: 'พนักงานยังไม่เช็กอิน',
    message: 'ชัยวัฒน์ สุขสวัสดิ์ (สาขาภูเก็ต) ยังไม่ได้เช็กอินวันนี้',
    type: 'attendance',
    is_read: false,
    link: '/manager/attendance',
    created_at: getToday() + 'T09:30:00Z',
  },
];
