import { NextResponse } from 'next/server';
import { canAccessCommerceBranch, getCommerceRequestContext, hasCommercePermission, requireSupabaseAdmin } from '@/lib/commerceServer';

export async function GET(request: Request) {
  try { const context = await getCommerceRequestContext(request); if (!context) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const branchId = new URL(request.url).searchParams.get('branch_id') || ''; if (!canAccessCommerceBranch(context.profile, branchId)) return NextResponse.json({ error: 'ไม่มีสิทธิ์สาขา' }, { status: 403 }); const { data, error } = await requireSupabaseAdmin().from('promotions').select('*, coupons(id, code, usage_limit, usage_count, valid_until, is_active), product_prices(id, product_id, product_unit_id, price, minimum_quantity, customer_type)').or(`branch_ids.cs.{${branchId}},branch_ids.eq.{}`).order('priority', { ascending: false }).order('created_at', { ascending: false }); if (error) throw error; return NextResponse.json({ promotions: data || [] }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Unable to load promotions' }, { status: 500 }); }
}

export async function POST(request: Request) {
  try {
    const context = await getCommerceRequestContext(request); if (!context) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const body = await request.json(); const branchId = String(body.branch_id || '');
    if (!hasCommercePermission(context.profile, 'promotion.manage', branchId)) return NextResponse.json({ error: 'ไม่มีสิทธิ์จัดการโปรโมชั่น' }, { status: 403 });
    const name = String(body.name || '').trim(); const productId = String(body.product_id || ''); const unitId = String(body.product_unit_id || ''); const price = Number(body.price); const minimumQuantity = Math.max(1, Number(body.minimum_quantity || 1));
    if (!name || !productId || !unitId || !Number.isFinite(price) || price < 0) return NextResponse.json({ error: 'ข้อมูลโปรโมชั่นไม่ครบ' }, { status: 400 });
    const startsAt = body.starts_at ? new Date(body.starts_at).toISOString() : new Date().toISOString(); const endsAt = body.ends_at ? new Date(body.ends_at).toISOString() : null; const code = `PROMO-${Date.now().toString(36).toUpperCase()}`;
    const admin = requireSupabaseAdmin(); const { data: promotion, error } = await admin.from('promotions').insert({ code, name, promotion_type: body.coupon_code ? 'coupon' : 'price', priority: 1000, branch_ids: [branchId], conditions: { product_id: productId, product_unit_id: unitId, minimum_quantity: minimumQuantity }, benefits: { price }, starts_at: startsAt, ends_at: endsAt, created_by_user_id: context.profile.id }).select('*').single(); if (error) throw error;
    const priceRows = ['retail', 'member', 'wholesale', 'dealer'].map((customerType) => ({ product_id: productId, product_unit_id: unitId, branch_id: branchId, customer_type: customerType, minimum_quantity: minimumQuantity, price, priority: 1000, starts_at: startsAt, ends_at: endsAt, is_active: true, promotion_id: promotion.id })); const priceResult = await admin.from('product_prices').insert(priceRows); if (priceResult.error) throw priceResult.error;
    if (typeof body.coupon_code === 'string' && body.coupon_code.trim()) { const coupon = await admin.from('coupons').insert({ promotion_id: promotion.id, code: body.coupon_code.trim().toUpperCase(), usage_limit: Number(body.usage_limit) > 0 ? Number(body.usage_limit) : null, valid_until: endsAt }); if (coupon.error) throw coupon.error; }
    await admin.from('commerce_audit_logs').insert({ actor_user_id: context.profile.id, branch_id: branchId, action: 'promotion.created', entity_type: 'promotion', entity_id: promotion.id, payload: { product_id: productId, price } }); return NextResponse.json({ promotion }, { status: 201 });
  } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Unable to create promotion' }, { status: 500 }); }
}

export async function PATCH(request: Request) {
  try { const context = await getCommerceRequestContext(request); if (!context) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const body = await request.json(); const branchId = String(body.branch_id || ''); if (!hasCommercePermission(context.profile, 'promotion.manage', branchId)) return NextResponse.json({ error: 'ไม่มีสิทธิ์จัดการโปรโมชั่น' }, { status: 403 }); const promotionId = String(body.promotion_id || ''); const isActive = Boolean(body.is_active); const admin = requireSupabaseAdmin(); const { data, error } = await admin.from('promotions').update({ is_active: isActive }).eq('id', promotionId).contains('branch_ids', [branchId]).select('*').single(); if (error) throw error; await admin.from('product_prices').update({ is_active: isActive }).eq('promotion_id', promotionId); await admin.from('coupons').update({ is_active: isActive }).eq('promotion_id', promotionId); return NextResponse.json({ promotion: data }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Unable to update promotion' }, { status: 500 }); }
}
