import { NextResponse } from 'next/server';
import { canAccessCommerceBranch, canManageCommerce, getCommerceRequestContext, requireSupabaseAdmin } from '@/lib/commerceServer';

export async function GET(request: Request) {
  const context = await getCommerceRequestContext(request); if (!context || !canManageCommerce(context.profile)) return NextResponse.json({ error: 'ไม่มีสิทธิ์ดูคอมมิชชัน' }, { status: 403 });
  const branchId = new URL(request.url).searchParams.get('branch_id') || context.profile.branch_id; if (!branchId || !canAccessCommerceBranch(context.profile, branchId)) return NextResponse.json({ error: 'ไม่มีสิทธิ์ดูสาขานี้' }, { status: 403 });
  const admin = requireSupabaseAdmin(); const {data:sales,error:salesError}=await admin.from('sales').select('id,receipt_number,completed_at').eq('branch_id',branchId).order('completed_at',{ascending:false}).limit(300); if(salesError)return NextResponse.json({error:salesError.message},{status:500}); const ids=(sales||[]).map(s=>s.id); if(!ids.length)return NextResponse.json({commissions:[]}); const {data:commissions,error}=await admin.from('referral_commissions').select('id,referrer_customer_id,referred_customer_id,sale_id,commission_rate,commission_amount,status,paid_at,created_at').in('sale_id',ids).order('created_at',{ascending:false});if(error)return NextResponse.json({error:error.message},{status:500});const customerIds=[...(new Set((commissions||[]).flatMap(c=>[c.referrer_customer_id,c.referred_customer_id])) )];const {data:customers}=customerIds.length?await admin.from('customers').select('id,full_name,member_code').in('id',customerIds):{data:[]};const byCustomer=new Map((customers||[]).map(c=>[c.id,c]));const bySale=new Map((sales||[]).map(s=>[s.id,s]));return NextResponse.json({commissions:(commissions||[]).map(c=>({...c,referrer:byCustomer.get(c.referrer_customer_id)||null,referred:byCustomer.get(c.referred_customer_id)||null,sale:bySale.get(c.sale_id)||null}))});
}
export async function PATCH(request:Request){try{const context=await getCommerceRequestContext(request);if(!context||!canManageCommerce(context.profile))return NextResponse.json({error:'ไม่มีสิทธิ์จ่ายคอมมิชชัน'},{status:403});const body=await request.json() as Record<string,unknown>;const id=typeof body.commission_id==='string'?body.commission_id:'';if(!id)return NextResponse.json({error:'ข้อมูลไม่ถูกต้อง'},{status:400});const admin=requireSupabaseAdmin();const {data:commission,error}=await admin.from('referral_commissions').select('id,sale_id,status').eq('id',id).maybeSingle();if(error||!commission)return NextResponse.json({error:'ไม่พบรายการ'},{status:404});const {data:sale}=await admin.from('sales').select('branch_id').eq('id',commission.sale_id).maybeSingle();if(!sale||!canAccessCommerceBranch(context.profile,sale.branch_id))return NextResponse.json({error:'ไม่มีสิทธิ์จ่ายรายการนี้'},{status:403});if(commission.status!=='pending')return NextResponse.json({error:'รายการนี้ไม่ได้อยู่ในสถานะรอจ่าย'},{status:409});const {data,error:updateError}=await admin.from('referral_commissions').update({status:'paid',paid_at:new Date().toISOString()}).eq('id',id).select().single();if(updateError)return NextResponse.json({error:updateError.message},{status:400});return NextResponse.json({commission:data});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'ทำรายการไม่สำเร็จ'},{status:500});}}
