'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { CommerceShell } from './CommerceShell';
import { CommerceInitialState } from './CommerceInitialState';
import { getAccessToken } from '@/lib/supabase';
import { CommerceBootstrap, PAYMENT_METHOD_LABELS, formatBaht, toNumber } from '@/lib/commerce';
type Session={id:string;register_name:string;status:string;opening_float:number|string;expected_cash:number|string;counted_cash:number|string|null;cash_variance:number|string|null;opened_at:string;closed_at:string|null;users:{name:string}|null};
type Closing={id:string;business_date:string;payment_totals:Record<string,number>;counted_cash:number|string;expected_cash:number|string;cash_variance:number|string;status:string;note:string|null};
async function req(path:string,init?:RequestInit){const token=await getAccessToken();const response=await fetch(path,{...init,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'ทำรายการไม่สำเร็จ');return body}
export default function DailyClosingWorkspace(){
  const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Bangkok'}),[date,setDate]=useState(today),[boot,setBoot]=useState<CommerceBootstrap|null>(null),[sessions,setSessions]=useState<Session[]>([]),[closing,setClosing]=useState<Closing|null>(null),[counted,setCounted]=useState('0'),[note,setNote]=useState(''),[status,setStatus]=useState('กำลังโหลดกะ…'),[loading,setLoading]=useState(true),[working,setWorking]=useState(false);
  const load=useCallback(async(nextDate=date)=>{try{const b=await req('/api/commerce/bootstrap') as CommerceBootstrap;const result=await req(`/api/commerce/daily-closing?branch_id=${b.branchId}&date=${nextDate}`) as {sessions:Session[];closing:Closing|null};setBoot(b);setSessions(result.sessions);setClosing(result.closing);setCounted(String(result.closing?.counted_cash??result.sessions.reduce((sum,item)=>sum+toNumber(item.counted_cash),0)));setNote(result.closing?.note||'');setStatus(result.sessions.some(item=>item.status==='open')?'ยังมีกะเปิดอยู่ ไม่สามารถปิดยอดวันได้':'ทุกกะปิดแล้ว พร้อมตรวจและส่งปิดยอด');}catch(error){setStatus(error instanceof Error?error.message:'โหลดไม่สำเร็จ')}finally{setLoading(false)}},[date]);useEffect(()=>{void load()},[load]);
  const totals=useMemo(()=>closing?.payment_totals||{},[closing]),expected=sessions.reduce((sum,item)=>sum+toNumber(item.expected_cash),0),canSubmit=!sessions.some(item=>item.status==='open')&&sessions.length>0&&closing?.status!=='locked';
  const submit=async(action:'submit'|'approve')=>{if(!boot)return;try{setWorking(true);await req('/api/commerce/daily-closing',{method:'POST',body:JSON.stringify({action,branch_id:boot.branchId,business_date:date,counted_cash:toNumber(counted),note})});await load(date)}catch(error){setStatus(error instanceof Error?error.message:'ปิดยอดไม่สำเร็จ')}finally{setWorking(false)}};
  if(loading)return <CommerceShell section="backoffice"><main className="mx-auto max-w-6xl p-5"><CommerceInitialState status={status} onRetry={()=>{setLoading(true);void load()}} label="กำลังรวมยอดทุกเครื่อง…"/></main></CommerceShell>;
  return <CommerceShell section="backoffice"><main className="mx-auto max-w-6xl p-5"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-slate-200 pb-4"><div><p className="text-xs font-medium text-primary-800">Cash control / Daily closing</p><h1 className="mt-1 text-2xl font-semibold">ปิดยอดประจำวัน</h1><p className="mt-1 text-sm text-slate-500">{status}</p></div><input type="date" value={date} max={today} onChange={event=>{setDate(event.target.value);setLoading(true)}} className="h-10 border border-slate-300 bg-white px-3 text-sm"/></header>
  <dl className="mt-5 grid border border-slate-200 bg-white sm:grid-cols-4"><Metric label="จำนวนกะ" value={`${sessions.length} กะ`}/><Metric label="ยอดเงินสดตามระบบ" value={formatBaht(closing?toNumber(closing.expected_cash):expected)}/><Metric label="เงินสดนับจริง" value={formatBaht(toNumber(closing?.counted_cash??counted))}/><Metric label="ขาด / เกิน" value={formatBaht(toNumber(closing?.cash_variance??toNumber(counted)-expected))} danger={Math.abs(toNumber(closing?.cash_variance??toNumber(counted)-expected))>0.01}/></dl>
  {closing?<section className="mt-5 border border-slate-200 bg-white"><div className="border-b border-slate-200 px-4 py-3"><h2 className="text-sm font-semibold">สรุปช่องทางชำระ · สถานะ {closing.status}</h2></div><div className="grid sm:grid-cols-3">{Object.entries(totals).map(([method,amount])=><Metric key={method} label={PAYMENT_METHOD_LABELS[method as keyof typeof PAYMENT_METHOD_LABELS]||method} value={formatBaht(toNumber(amount))}/>)}</div></section>:null}
  <section className="mt-5 overflow-x-auto border border-slate-200 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">เครื่อง / พนักงาน</th><th className="px-4 py-3">เวลา</th><th className="px-4 py-3 text-right">เงินตามระบบ</th><th className="px-4 py-3 text-right">นับจริง</th><th className="px-4 py-3 text-right">ส่วนต่าง</th><th className="px-4 py-3">สถานะ</th></tr></thead><tbody>{sessions.map(item=><tr key={item.id} className="border-t border-slate-100"><td className="px-4 py-3"><p className="font-medium">{item.register_name}</p><p className="text-xs text-slate-500">{item.users?.name||'-'}</p></td><td className="px-4 py-3 text-xs text-slate-500">{new Date(item.opened_at).toLocaleTimeString('th-TH')} – {item.closed_at?new Date(item.closed_at).toLocaleTimeString('th-TH'):'ยังไม่ปิด'}</td><td className="px-4 py-3 text-right tabular-nums">{formatBaht(toNumber(item.expected_cash))}</td><td className="px-4 py-3 text-right tabular-nums">{item.counted_cash==null?'-':formatBaht(toNumber(item.counted_cash))}</td><td className="px-4 py-3 text-right tabular-nums">{item.cash_variance==null?'-':formatBaht(toNumber(item.cash_variance))}</td><td className="px-4 py-3">{item.status}</td></tr>)}{!sessions.length?<tr><td colSpan={6} className="px-4 py-12 text-center text-slate-500">ไม่มีกะในวันที่เลือก</td></tr>:null}</tbody></table></section>
  <section className="mt-5 border border-slate-200 bg-white p-4"><div className="grid gap-4 sm:grid-cols-[14rem_1fr_auto]"><label className="text-xs font-medium">เงินสดนับจริงรวม<input type="number" min="0" step="0.01" disabled={closing?.status==='locked'} value={counted} onChange={event=>setCounted(event.target.value)} className="mt-1.5 h-10 w-full border border-slate-300 px-3 text-right text-sm"/></label><label className="text-xs font-medium">หมายเหตุ<input disabled={closing?.status==='locked'} value={note} onChange={event=>setNote(event.target.value)} className="mt-1.5 h-10 w-full border border-slate-300 px-3 text-sm" placeholder="อธิบายส่วนต่างหรือเหตุการณ์ของวัน"/></label><div className="flex items-end gap-2">{closing?.status==='submitted'?<button disabled={working} onClick={()=>void submit('approve')} className="h-10 bg-slate-900 px-4 text-sm font-semibold text-white">ตรวจแล้ว · ล็อกยอด</button>:<button disabled={working||!canSubmit} onClick={()=>void submit('submit')} className="h-10 bg-primary-800 px-4 text-sm font-semibold text-white disabled:bg-slate-300">ส่งปิดยอดวัน</button>}</div></div></section></main></CommerceShell>}
function Metric({label,value,danger=false}:{label:string;value:string;danger?:boolean}){return <div className="border-b border-r border-slate-200 px-4 py-4"><dt className="text-xs text-slate-500">{label}</dt><dd className={`mt-1 text-lg font-semibold tabular-nums ${danger?'text-red-700':'text-slate-900'}`}>{value}</dd></div>}
