'use client';

import { useCallback, useEffect, useState } from 'react';
import { CommerceShell } from '@/components/commerce/CommerceShell';
import { CommerceInitialState } from '@/components/commerce/CommerceInitialState';
import { CommerceBootstrap, formatBaht, toNumber } from '@/lib/commerce';
import { getAccessToken } from '@/lib/supabase';

type OrderItem = { id: string; product_name_snapshot: string; unit_name_snapshot: string; quantity: number | string; line_total: number | string };
type OnlineOrder = { id: string; order_number: string; customer_name: string; customer_phone: string; fulfillment_method: 'pickup' | 'delivery'; delivery_address: string | null; status: string; grand_total: number | string; payment_method: string; note: string | null; placed_at: string; online_order_items: OrderItem[] };
const statusLabels: Record<string, string> = { awaiting_payment: 'รอตรวจชำระเงิน', paid: 'ชำระแล้ว', packing: 'กำลังจัดสินค้า', ready_for_pickup: 'พร้อมรับที่สาขา', shipping: 'กำลังจัดส่ง', completed: 'เสร็จสมบูรณ์', cancelled: 'ยกเลิก' };
const paymentLabels: Record<string, string> = { bank_transfer: 'โอนเงิน', qr: 'QR', cash_on_pickup: 'ชำระเมื่อรับสินค้า' };
const actions: Record<string, Array<{ status: string; label: string }>> = { awaiting_payment: [{ status: 'paid', label: 'ยืนยันชำระเงิน' }, { status: 'cancelled', label: 'ยกเลิก' }], paid: [{ status: 'packing', label: 'เริ่มจัดสินค้า' }, { status: 'cancelled', label: 'ยกเลิก' }], packing: [{ status: 'ready_for_pickup', label: 'พร้อมรับสินค้า' }, { status: 'shipping', label: 'ส่งพัสดุ' }, { status: 'cancelled', label: 'ยกเลิก' }], ready_for_pickup: [{ status: 'completed', label: 'ส่งมอบแล้ว' }, { status: 'cancelled', label: 'ยกเลิก' }], shipping: [{ status: 'completed', label: 'จัดส่งสำเร็จ' }, { status: 'cancelled', label: 'ยกเลิก' }] };

async function commerceFetch(path: string, init?: RequestInit) { const token = await getAccessToken(); const response = await fetch(path, { ...init, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...init?.headers } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || 'ทำรายการไม่สำเร็จ'); return body; }

export default function OnlineOrdersWorkspace() {
  const [bootstrap, setBootstrap] = useState<CommerceBootstrap | null>(null); const [orders, setOrders] = useState<OnlineOrder[]>([]); const [status, setStatus] = useState('กำลังโหลดคำสั่งซื้อออนไลน์…'); const [working, setWorking] = useState(false);
  const load = useCallback(async (branchId?: string) => { try { setStatus('กำลังโหลดคำสั่งซื้อออนไลน์…'); const base = await commerceFetch(`/api/commerce/bootstrap${branchId ? `?branch_id=${encodeURIComponent(branchId)}` : ''}`) as CommerceBootstrap; const result = await commerceFetch(`/api/commerce/online-orders?branch_id=${encodeURIComponent(base.branchId)}`) as { orders: OnlineOrder[] }; setBootstrap(base); setOrders(result.orders); setStatus(result.orders.length ? 'ติดตามและจัดการสถานะคำสั่งซื้อได้จากหน้านี้' : 'ยังไม่มีคำสั่งซื้อออนไลน์ในสาขานี้'); } catch (error) { setStatus(error instanceof Error ? error.message : 'โหลดข้อมูลไม่สำเร็จ'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const updateStatus = async (order: OnlineOrder, nextStatus: string) => { if (!bootstrap) return; try { setWorking(true); await commerceFetch('/api/commerce/online-orders', { method: 'PATCH', body: JSON.stringify({ branch_id: bootstrap.branchId, order_id: order.id, status: nextStatus }) }); await load(bootstrap.branchId); setStatus(`อัปเดต ${order.order_number} แล้ว`); } catch (error) { setStatus(error instanceof Error ? error.message : 'เปลี่ยนสถานะไม่สำเร็จ'); } finally { setWorking(false); } };
  if (!bootstrap) return <CommerceShell section="online-orders"><main className="mx-auto max-w-[1420px] px-3 py-5 sm:px-5"><CommerceInitialState status={status} onRetry={() => void load()} label="กำลังโหลดคำสั่งซื้อออนไลน์…" /></main></CommerceShell>;
  return <CommerceShell section="online-orders"><div className="mx-auto max-w-[1420px] px-3 py-5 sm:px-5"><header className="border-b border-slate-200 pb-4"><p className="text-xs font-medium text-primary-800">Commerce / Online orders</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">คำสั่งซื้อออนไลน์</h1><p className="mt-1 text-sm text-slate-500">{status}</p></header><section className="mt-5 border border-slate-200 bg-white"><div className="border-b border-slate-200 px-4 py-3"><h2 className="text-sm font-semibold">คิวดำเนินการ</h2></div><div className="divide-y divide-slate-200">{orders.map((order) => <article key={order.id} className="px-4 py-4 sm:px-5"><div className="grid gap-3 lg:grid-cols-[10rem_minmax(0,1fr)_12rem_auto]"><div><p className="text-xs text-slate-500">{new Date(order.placed_at).toLocaleString('th-TH')}</p><p className="mt-1 font-semibold">{order.order_number}</p><p className="mt-1 text-xs text-primary-800">{statusLabels[order.status] || order.status}</p></div><div><p className="font-medium">{order.customer_name} <span className="font-normal text-slate-500">{order.customer_phone}</span></p><p className="mt-1 text-sm text-slate-600">{order.online_order_items.map((item) => `${item.product_name_snapshot} × ${item.quantity} ${item.unit_name_snapshot}`).join(' · ')}</p><p className="mt-1 text-xs text-slate-500">{order.fulfillment_method === 'delivery' ? `จัดส่ง: ${order.delivery_address}` : 'รับสินค้าที่สาขา'} · {paymentLabels[order.payment_method] || order.payment_method}{order.note ? ` · ${order.note}` : ''}</p></div><p className="text-left font-semibold tabular-nums lg:text-right">{formatBaht(toNumber(order.grand_total))}</p><div className="flex flex-wrap items-start gap-2 lg:justify-end">{(actions[order.status] || []).map((action) => <button key={action.status} type="button" disabled={working} onClick={() => void updateStatus(order, action.status)} className={action.status === 'cancelled' ? 'text-xs text-red-700 disabled:text-slate-300' : 'border border-primary-700 px-2.5 py-1.5 text-xs font-medium text-primary-800 disabled:border-slate-200 disabled:text-slate-300'}>{action.label}</button>)}</div></div></article>)}{!orders.length ? <p className="px-4 py-14 text-center text-sm text-slate-500">ยังไม่มีคำสั่งซื้อออนไลน์</p> : null}</div></section></div></CommerceShell>;
}
