'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { CommerceInitialState } from '@/components/commerce/CommerceInitialState';
import { CommerceShell } from '@/components/commerce/CommerceShell';
import CommerceProductPicker from '@/components/commerce/CommerceProductPicker';
import CommerceUnitPicker from '@/components/commerce/CommerceUnitPicker';
import { type CommerceBootstrap, formatBaht, toNumber } from '@/lib/commerce';
import { getAccessToken } from '@/lib/supabase';

type Promotion = { id: string; code: string; name: string; is_active: boolean; starts_at: string | null; ends_at: string | null; benefits: { price?: number }; product_prices: Array<{ product_id: string; product_unit_id: string; price: number | string; minimum_quantity: number | string }>; coupons: Array<{ code: string; usage_count: number; usage_limit: number | null }> };
async function request(path: string, init?: RequestInit) { const token = await getAccessToken(); const response = await fetch(path, { ...init, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || 'ทำรายการไม่สำเร็จ'); return body; }

export default function PromotionWorkspace() {
  const [bootstrap, setBootstrap] = useState<CommerceBootstrap | null>(null); const [promotions, setPromotions] = useState<Promotion[]>([]); const [status, setStatus] = useState('กำลังโหลดโปรโมชั่น…'); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false);
  const [form, setForm] = useState({ name: '', product_id: '', product_unit_id: '', price: '', minimum_quantity: '1', starts_at: '', ends_at: '', coupon_code: '', usage_limit: '' });
  const load = useCallback(async (branchId?: string) => { try { const boot = await request(`/api/commerce/bootstrap${branchId ? `?branch_id=${encodeURIComponent(branchId)}` : ''}`) as CommerceBootstrap; const response = await request(`/api/commerce/promotions?branch_id=${encodeURIComponent(boot.branchId)}`) as { promotions: Promotion[] }; setBootstrap(boot); setPromotions(response.promotions); setStatus(response.promotions.length ? `${response.promotions.length} โปรโมชั่นในสาขานี้` : 'ยังไม่มีโปรโมชั่น'); } catch (error) { setStatus(error instanceof Error ? error.message : 'โหลดโปรโมชั่นไม่สำเร็จ'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const product = bootstrap?.products.find((item) => item.id === form.product_id); const unit = product?.units.find((item) => item.id === form.product_unit_id);
  const create = async (event: FormEvent) => { event.preventDefault(); if (!bootstrap) return; try { setWorking(true); await request('/api/commerce/promotions', { method: 'POST', body: JSON.stringify({ branch_id: bootstrap.branchId, ...form }) }); setForm({ name: '', product_id: '', product_unit_id: '', price: '', minimum_quantity: '1', starts_at: '', ends_at: '', coupon_code: '', usage_limit: '' }); await load(bootstrap.branchId); setStatus('เปิดใช้โปรโมชั่นแล้ว ราคาใหม่จะแสดงที่ POS พร้อมเหตุผล “ราคาโปรโมชั่น”'); } catch (error) { setStatus(error instanceof Error ? error.message : 'สร้างโปรโมชั่นไม่สำเร็จ'); } finally { setWorking(false); } };
  const toggle = async (promotion: Promotion) => { if (!bootstrap) return; try { setWorking(true); await request('/api/commerce/promotions', { method: 'PATCH', body: JSON.stringify({ branch_id: bootstrap.branchId, promotion_id: promotion.id, is_active: !promotion.is_active }) }); await load(bootstrap.branchId); } catch (error) { setStatus(error instanceof Error ? error.message : 'เปลี่ยนสถานะไม่สำเร็จ'); } finally { setWorking(false); } };
  const productById = useMemo(() => new Map((bootstrap?.products || []).map((item) => [item.id, item])), [bootstrap?.products]);

  if (loading || !bootstrap) return <CommerceShell section="backoffice"><main className="mx-auto max-w-[1380px] px-4 py-5"><CommerceInitialState status={status} onRetry={() => void load()} label="กำลังโหลดโปรโมชั่น…" /></main></CommerceShell>;
  return <CommerceShell section="backoffice"><main className="mx-auto max-w-[1380px] px-4 py-5"><header className="border-b border-slate-200 pb-4"><p className="text-xs font-medium text-primary-800">Commerce / Pricing</p><h1 className="mt-1 text-2xl font-semibold">โปรโมชั่นและคูปอง</h1><p className="mt-1 text-sm text-slate-500">{status}</p></header>
    <div className="mt-5 grid gap-5 lg:grid-cols-[22rem_minmax(0,1fr)]"><form onSubmit={create} className="h-fit border border-slate-200 bg-white p-4"><h2 className="text-sm font-semibold">สร้างราคาโปรโมชั่น</h2><label className="mt-3 block text-xs font-medium">ชื่อโปรโมชั่น<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="mt-1.5 h-10 w-full border border-slate-300 px-3 text-sm" /></label><label className="mt-3 block text-xs font-medium">สินค้า<CommerceProductPicker products={bootstrap.products} value={form.product_id} onValueChange={(productId, selectedProduct) => setForm({ ...form, product_id: productId, product_unit_id: selectedProduct?.units[0]?.id || '' })} placeholder="เลือกสินค้า" aria-label="สินค้าโปรโมชั่น" className="mt-1.5 h-10 w-full" /></label><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-xs font-medium">หน่วย<CommerceUnitPicker units={product?.units || []} product={product} value={form.product_unit_id} onValueChange={(unitId) => setForm({ ...form, product_unit_id: unitId })} disabled={!product} placeholder={product ? 'เลือกหน่วย' : 'เลือกสินค้าก่อน'} className="mt-1.5 h-10 w-full" /></label><label className="text-xs font-medium">ขั้นต่ำ<input required min="1" step="0.001" type="number" value={form.minimum_quantity} onChange={(event) => setForm({ ...form, minimum_quantity: event.target.value })} className="mt-1.5 h-10 w-full border border-slate-300 px-3 text-sm" /></label></div><label className="mt-3 block text-xs font-medium">ราคาโปรโมชั่น<input required min="0" step="0.01" type="number" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} className="mt-1.5 h-10 w-full border border-slate-300 px-3 text-sm" /></label>{unit ? <p className="mt-1 text-xs text-slate-500">ราคาปัจจุบัน {formatBaht(unit.salePrice)} / {unit.name}</p> : null}<div className="mt-3 grid grid-cols-2 gap-3"><label className="text-xs font-medium">เริ่มใช้<input type="datetime-local" value={form.starts_at} onChange={(event) => setForm({ ...form, starts_at: event.target.value })} className="mt-1.5 h-10 w-full border border-slate-300 px-2 text-xs" /></label><label className="text-xs font-medium">สิ้นสุด<input type="datetime-local" value={form.ends_at} onChange={(event) => setForm({ ...form, ends_at: event.target.value })} className="mt-1.5 h-10 w-full border border-slate-300 px-2 text-xs" /></label></div><label className="mt-3 block text-xs font-medium">รหัสคูปอง (ถ้ามี)<input value={form.coupon_code} onChange={(event) => setForm({ ...form, coupon_code: event.target.value.toUpperCase() })} className="mt-1.5 h-10 w-full border border-slate-300 px-3 font-mono text-sm" /></label><button disabled={working} className="mt-4 h-10 w-full bg-primary-800 text-sm font-semibold text-white disabled:bg-slate-300">เปิดใช้โปรโมชั่น</button></form>
      <section className="border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">โปรโมชั่น</th><th className="px-4 py-3">สินค้า / เงื่อนไข</th><th className="px-4 py-3 text-right">ราคา</th><th className="px-4 py-3">ช่วงเวลา</th><th className="px-4 py-3 text-right">สถานะ</th></tr></thead><tbody>{promotions.map((promotion) => { const price = promotion.product_prices[0]; const item = price ? productById.get(price.product_id) : null; return <tr key={promotion.id} className="border-t border-slate-100"><td className="px-4 py-3"><p className="font-medium">{promotion.name}</p><p className="mt-0.5 font-mono text-[11px] text-slate-500">{promotion.coupons[0]?.code || promotion.code}</p></td><td className="px-4 py-3"><p>{item?.name || 'สินค้า'}</p><p className="mt-0.5 text-xs text-slate-500">ขั้นต่ำ {toNumber(price?.minimum_quantity).toLocaleString('th-TH')} หน่วยขาย</p></td><td className="px-4 py-3 text-right font-semibold">{formatBaht(toNumber(price?.price || promotion.benefits.price))}</td><td className="px-4 py-3 text-xs text-slate-500">{promotion.starts_at ? new Date(promotion.starts_at).toLocaleString('th-TH') : 'ทันที'}<br />ถึง {promotion.ends_at ? new Date(promotion.ends_at).toLocaleString('th-TH') : 'ไม่กำหนด'}</td><td className="px-4 py-3 text-right"><button disabled={working} onClick={() => void toggle(promotion)} className={`h-8 border px-3 text-xs font-semibold ${promotion.is_active ? 'border-primary-300 text-primary-800' : 'border-slate-300 text-slate-500'}`}>{promotion.is_active ? 'เปิดใช้งาน' : 'ปิดใช้งาน'}</button></td></tr>; })}{!promotions.length ? <tr><td colSpan={5} className="px-4 py-16 text-center text-sm text-slate-500">ยังไม่มีโปรโมชั่นในสาขานี้</td></tr> : null}</tbody></table></div></section></div>
  </main></CommerceShell>;
}
