'use client';
/* eslint-disable @next/next/no-img-element */

import Select from '@/components/ui/Select';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { CommerceInitialState } from '@/components/commerce/CommerceInitialState';
import { CommerceShell } from '@/components/commerce/CommerceShell';
import type { CommerceBootstrap } from '@/lib/commerce';
import { getAccessToken } from '@/lib/supabase';

type Session = { id: string; count_number: string; status: string; scope: Record<string, unknown>; created_at: string; note: string | null };
type Item = { id: string; product_id: string; product_unit_id: string | null; system_quantity: number | string; counted_quantity: number | string | null; variance: number | string; reason: string | null; products: { sku: string; barcode: string | null; name: string; image_url: string | null; base_unit_code: string; unit_inventory_mode: 'shared_base' | 'separate_unit' }; product_units: { name: string; code: string; conversion_to_base: number | string; image_url: string | null } | null };
async function request(path: string, init?: RequestInit) { const token = await getAccessToken(); const response = await fetch(path, { ...init, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || 'ทำรายการไม่สำเร็จ'); return body; }

export default function StockCountWorkspace() {
  const [bootstrap, setBootstrap] = useState<CommerceBootstrap | null>(null);
  const [sessions, setSessions] = useState<Session[]>([]);
  const [items, setItems] = useState<Item[]>([]);
  const [selectedId, setSelectedId] = useState('');
  const [categoryId, setCategoryId] = useState('');
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('กำลังโหลดรอบตรวจนับ…');
  const [working, setWorking] = useState(false);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async (branchId?: string, sessionId?: string) => {
    try {
      const boot = await request(`/api/commerce/bootstrap${branchId ? `?branch_id=${encodeURIComponent(branchId)}` : ''}`) as CommerceBootstrap;
      const response = await request(`/api/commerce/stock-counts?branch_id=${encodeURIComponent(boot.branchId)}${sessionId ? `&session_id=${encodeURIComponent(sessionId)}` : ''}`) as { sessions: Session[]; items: Item[] };
      setBootstrap(boot); setSessions(response.sessions); setItems(response.items); if (sessionId) setSelectedId(sessionId);
      setStatus(sessionId ? `${response.items.length} รายการในรอบตรวจนับ` : response.sessions.length ? 'เลือกรอบเพื่อตรวจนับหรืออนุมัติ' : 'ยังไม่มีรอบตรวจนับในสาขานี้');
    } catch (error) { setStatus(error instanceof Error ? error.message : 'โหลดรอบตรวจนับไม่สำเร็จ'); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);

  const create = async () => { if (!bootstrap) return; try { setWorking(true); const response = await request('/api/commerce/stock-counts', { method: 'POST', body: JSON.stringify({ action: 'create', branch_id: bootstrap.branchId, category_id: categoryId || null }) }) as { session: Session }; await load(bootstrap.branchId, response.session.id); setStatus(`เปิดรอบ ${response.session.count_number} แล้ว เริ่มนับได้ทันที`); } catch (error) { setStatus(error instanceof Error ? error.message : 'เปิดรอบไม่สำเร็จ'); } finally { setWorking(false); } };
  const count = async (item: Item, countedQuantity: string, reason: string) => { if (!bootstrap || !selectedId) return; try { await request('/api/commerce/stock-counts', { method: 'POST', body: JSON.stringify({ action: 'count', branch_id: bootstrap.branchId, session_id: selectedId, item_id: item.id, counted_quantity: countedQuantity, reason }) }); setItems((current) => current.map((row) => row.id === item.id ? { ...row, counted_quantity: countedQuantity, reason, variance: Number(countedQuantity) - Number(row.system_quantity) } : row)); setStatus(`บันทึกยอด ${item.products.name} แล้ว`); } catch (error) { setStatus(error instanceof Error ? error.message : 'บันทึกยอดไม่สำเร็จ'); } };
  const action = async (nextAction: 'submit' | 'approve' | 'post') => { if (!bootstrap || !selectedId) return; try { setWorking(true); await request('/api/commerce/stock-counts', { method: 'POST', body: JSON.stringify({ action: nextAction, branch_id: bootstrap.branchId, session_id: selectedId }) }); await load(bootstrap.branchId, selectedId); setStatus(nextAction === 'submit' ? 'ส่งผลตรวจนับให้ผู้จัดการตรวจแล้ว' : nextAction === 'approve' ? 'อนุมัติส่วนต่างแล้ว' : 'โพสต์ส่วนต่างเข้า Stock movement แล้ว'); } catch (error) { setStatus(error instanceof Error ? error.message : 'ทำรายการไม่สำเร็จ'); } finally { setWorking(false); } };
  const selected = sessions.find((session) => session.id === selectedId);
  const visibleItems = useMemo(() => { const needle = query.trim().toLocaleLowerCase(); return items.filter((item) => !needle || `${item.products.sku} ${item.products.barcode || ''} ${item.products.name} ${item.product_units?.name || ''}`.toLocaleLowerCase().includes(needle)); }, [items, query]);
  const counted = items.filter((item) => item.counted_quantity != null).length;
  const varianceItems = items.filter((item) => item.counted_quantity != null && Math.abs(Number(item.variance)) > 0.0001).length;

  if (loading || !bootstrap) return <CommerceShell section="backoffice"><main className="mx-auto max-w-[1480px] px-4 py-5"><CommerceInitialState status={status} onRetry={() => void load()} label="กำลังโหลดรอบตรวจนับ…" /></main></CommerceShell>;
  return <CommerceShell section="backoffice"><main className="mx-auto max-w-[1480px] px-4 py-5 sm:px-5"><header className="flex flex-wrap items-end justify-between gap-3 border-b border-slate-200 pb-4"><div><p className="text-xs font-medium text-primary-800">Commerce / Inventory count</p><h1 className="mt-1 text-2xl font-semibold">ตรวจนับสต๊อก</h1><p className="mt-1 text-sm text-slate-500">{status}</p></div><div className="flex gap-2"><Select value={categoryId} onChange={(event) => setCategoryId(event.target.value)} className="h-9 border border-slate-300 bg-white px-2 text-sm"><option value="">สินค้าทุกหมวด</option>{bootstrap.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</Select><button disabled={working} onClick={() => void create()} className="h-9 bg-primary-800 px-4 text-sm font-semibold text-white disabled:bg-slate-300">เปิดรอบใหม่</button></div></header>
    <div className="mt-5 grid gap-5 xl:grid-cols-[22rem_minmax(0,1fr)]"><aside className="border border-slate-200 bg-white"><div className="border-b border-slate-200 px-4 py-3"><h2 className="text-sm font-semibold">รอบตรวจนับ</h2></div><div className="divide-y divide-slate-100">{sessions.map((session) => <button type="button" key={session.id} onClick={() => void load(bootstrap.branchId, session.id)} className={`w-full px-4 py-3 text-left hover:bg-slate-50 ${selectedId === session.id ? 'bg-primary-50' : ''}`}><div className="flex justify-between gap-2"><span className="text-sm font-semibold">{session.count_number}</span><span className="text-xs font-medium text-primary-800">{session.status}</span></div><p className="mt-1 text-xs text-slate-500">{new Date(session.created_at).toLocaleString('th-TH')}</p></button>)}{!sessions.length ? <p className="px-4 py-12 text-center text-sm text-slate-500">ยังไม่มีรอบตรวจนับ</p> : null}</div></aside>
      <section className="min-w-0 border border-slate-200 bg-white"><div className="flex flex-wrap items-center gap-3 border-b border-slate-200 p-3"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ค้นหา SKU, บาร์โค้ด, ชื่อสินค้า" className="h-9 min-w-56 flex-1 border border-slate-300 px-3 text-sm" /><span className="text-xs text-slate-500">นับแล้ว {counted}/{items.length} · ต่าง {varianceItems} รายการ</span>{selected?.status === 'counting' ? <button disabled={working} onClick={() => void action('submit')} className="h-9 border border-primary-700 px-3 text-xs font-semibold text-primary-800">ส่งตรวจ</button> : null}{selected?.status === 'review' ? <button disabled={working} onClick={() => void action('approve')} className="h-9 bg-primary-800 px-3 text-xs font-semibold text-white">อนุมัติ</button> : null}{selected?.status === 'approved' ? <button disabled={working} onClick={() => void action('post')} className="h-9 bg-slate-900 px-3 text-xs font-semibold text-white">โพสต์ปรับยอด</button> : null}</div><div className="max-h-[68dvh] overflow-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs text-slate-500"><tr><th className="px-3 py-3">SKU / สินค้า</th><th className="px-3 py-3 text-right">ยอดระบบ</th><th className="px-3 py-3 text-right">ยอดนับจริง</th><th className="px-3 py-3 text-right">ส่วนต่าง</th><th className="px-3 py-3">เหตุผล</th></tr></thead><tbody>{visibleItems.map((item) => <StockCountRow key={item.id} item={item} editable={selected?.status === 'counting'} onSave={count} />)}{!visibleItems.length ? <tr><td colSpan={5} className="px-4 py-16 text-center text-sm text-slate-500">{selectedId ? 'ไม่พบสินค้าที่ค้นหา' : 'เลือกรอบตรวจนับด้านซ้าย'}</td></tr> : null}</tbody></table></div></section>
    </div></main></CommerceShell>;
}

function StockCountRow({ item, editable, onSave }: { item: Item; editable: boolean; onSave: (item: Item, quantity: string, reason: string) => Promise<void> }) {
  const [quantity, setQuantity] = useState(item.counted_quantity == null ? '' : String(item.counted_quantity)); const [reason, setReason] = useState(item.reason || ''); const variance = quantity === '' ? null : Number(quantity) - Number(item.system_quantity);
  const image = item.product_units?.image_url || item.products.image_url;
  return <tr className="border-t border-slate-100"><td className="px-3 py-3"><div className="flex items-center gap-2"><span className="grid h-9 w-9 shrink-0 place-items-center overflow-hidden border border-slate-200 bg-slate-50">{image ? <img src={image} alt="" className="h-full w-full object-cover" /> : null}</span><div className="min-w-0"><p className="font-medium">{item.products.name}{item.product_units ? <span className="ml-2 bg-primary-50 px-2 py-0.5 text-[11px] font-medium text-primary-800">{item.product_units.name}</span> : null}</p><p className="mt-0.5 text-xs text-slate-500">{item.products.sku}{item.products.barcode ? ` · ${item.products.barcode}` : ''} · {item.product_units ? `1 ${item.product_units.name} = ${item.product_units.conversion_to_base} ${item.products.base_unit_code}` : item.products.base_unit_code}</p></div></div></td><td className="px-3 py-3 text-right tabular-nums">{Number(item.system_quantity).toLocaleString('th-TH')}</td><td className="px-3 py-3 text-right"><input disabled={!editable} type="number" min="0" step="0.001" value={quantity} onChange={(event) => setQuantity(event.target.value)} onBlur={() => { if (quantity !== '') void onSave(item, quantity, reason); }} className="h-9 w-28 border border-slate-300 px-2 text-right tabular-nums disabled:border-transparent disabled:bg-transparent" /></td><td className={`px-3 py-3 text-right font-semibold tabular-nums ${variance == null || variance === 0 ? 'text-slate-400' : variance > 0 ? 'text-primary-800' : 'text-red-700'}`}>{variance == null ? '-' : variance > 0 ? `+${variance.toLocaleString('th-TH')}` : variance.toLocaleString('th-TH')}</td><td className="px-3 py-3"><input disabled={!editable} value={reason} onChange={(event) => setReason(event.target.value)} onBlur={() => { if (quantity !== '') void onSave(item, quantity, reason); }} placeholder={variance ? 'ระบุเหตุผลส่วนต่าง' : 'หมายเหตุ'} className="h-9 w-full min-w-40 border border-slate-300 px-2 text-xs disabled:border-transparent disabled:bg-transparent" /></td></tr>;
}
